import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut, EmailAuthProvider, reauthenticateWithCredential } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, collection, query, orderBy, onSnapshot, doc, updateDoc, deleteDoc, getDoc, setDoc, runTransaction, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { firebaseConfig, ADMIN_EMAIL } from "./firebase-runtime.js";

const CLOUDINARY_CLOUD_NAME = "k5bsrnx1";
const CLOUDINARY_UPLOAD_PRESET = "new-conquerors";
const CLOUDINARY_URL = `https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD_NAME}/image/upload`;
const app = initializeApp(firebaseConfig); const auth = getAuth(app); const db = getFirestore(app);
const loginView=document.getElementById("loginView"), dashboardView=document.getElementById("dashboardView");
const email=document.getElementById("email"), password=document.getElementById("password"), loginBtn=document.getElementById("loginBtn"), loginError=document.getElementById("loginError");
const membersBody=document.getElementById("membersBody"), search=document.getElementById("search"), statusFilter=document.getElementById("statusFilter"), modal=document.getElementById("detailModal"), detailBody=document.getElementById("detailBody");
const logoutBtn=document.getElementById("logoutBtn");
let loginWasExplicit = sessionStorage.getItem("bayiiraAdminExplicitLogin") === "1";
const idModal=document.getElementById("idModal"), idPassport=document.getElementById("idPassport"), idFullName=document.getElementById("idFullName"), idRegNo=document.getElementById("idRegNo"), idMembership=document.getElementById("idMembership"), idCategory=document.getElementById("idCategory"), idPhone=document.getElementById("idPhone"), idSignature=document.getElementById("idSignature"), idBarcode=document.getElementById("idBarcode"), idQr=document.getElementById("idQr");
const adminDpInput=document.getElementById("adminDpInput"), adminDpPreview=document.getElementById("adminDpPreview"), saveAdminDpBtn=document.getElementById("saveAdminDpBtn"), adminProfileMsg=document.getElementById("adminProfileMsg");
let members=[]; let selectedMember=null;
function msg(el,text){el.textContent=text;el.style.display="block"} function hide(el){el.style.display="none"} function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#039;"}[m]))}
function dateText(v){if(!v)return "—";try{return v.toDate().toLocaleString()}catch{return String(v)}}
function statusBadge(s){s=s||"pending";return `<span class="badge badge-${esc(s)}">${esc(s.toUpperCase())}</span>`}
async function uploadToCloudinary(file, folder){if(!file)throw new Error("Please select an image.");if(file.size>5*1024*1024)throw new Error("Image must be 5 MB or smaller.");const body=new FormData();body.append("file",file);body.append("upload_preset",CLOUDINARY_UPLOAD_PRESET);body.append("folder",folder);let r;try{r=await fetch(CLOUDINARY_URL,{method:"POST",body,mode:"cors",credentials:"omit"})}catch(e){throw new Error(`Cloudinary could not be reached. Check your internet connection and confirm that upload preset "${CLOUDINARY_UPLOAD_PRESET}" exists and is set to Unsigned in Cloudinary. (${e.message||"network error"})`)}let j={};try{j=await r.json()}catch(_){}if(!r.ok||!j.secure_url)throw new Error(`Cloudinary upload failed: ${j.error?.message||`HTTP ${r.status}`}. Cloud: ${CLOUDINARY_CLOUD_NAME}; Preset: ${CLOUDINARY_UPLOAD_PRESET}`);return j.secure_url}

if(!loginBtn||!email||!password||!loginView||!dashboardView||!loginError||!membersBody||!search||!statusFilter||!modal||!detailBody){console.error("Bayiira admin page: required dashboard elements missing.")}else loginBtn.onclick=async()=>{hide(loginError);loginBtn.disabled=true;loginBtn.textContent="Signing in...";try{const cred=await signInWithEmailAndPassword(auth,email.value.trim(),password.value);if(cred.user.email?.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){await signOut(auth);throw new Error("This account is not authorized as administrator.")}loginWasExplicit=true;sessionStorage.setItem("bayiiraAdminExplicitLogin","1");loginView.classList.add("hidden");dashboardView.classList.remove("hidden");await loadAdminProfile(cred.user);listenMembers()}catch(e){console.error("Administrator login failed:",e);const code=e?.code||"";const message=code==="auth/invalid-credential"||code==="auth/wrong-password"?"Invalid administrator email or password.":code==="auth/user-not-found"?"Administrator account was not found.":e?.message||"Login failed. Please try again.";msg(loginError,message)}finally{loginBtn.disabled=false;loginBtn.textContent="LOGIN"}};
password.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();loginBtn.click()}});
logoutBtn?.addEventListener("click",async()=>{logoutBtn.disabled=true;logoutBtn.textContent="Signing out...";try{sessionStorage.removeItem("bayiiraAdminExplicitLogin");loginWasExplicit=false;await signOut(auth);dashboardView.classList.add("hidden");loginView.classList.remove("hidden");password.value="";hide(loginError);email.focus();window.scrollTo({top:0,behavior:"auto"})}finally{logoutBtn.disabled=false;logoutBtn.textContent="Sign out"}});

onAuthStateChanged(auth,async user=>{if(user&&user.email?.toLowerCase()===ADMIN_EMAIL.toLowerCase()&&loginWasExplicit){loginView.classList.add("hidden");dashboardView.classList.remove("hidden");await loadAdminProfile(user);listenMembers()}else{dashboardView.classList.add("hidden");loginView.classList.remove("hidden");if(user&&!loginWasExplicit){await signOut(auth)}}});

async function loadAdminProfile(user){document.getElementById("adminProfileEmail").textContent=user.email||ADMIN_EMAIL;const snap=await getDoc(doc(db,"adminProfiles",user.uid));if(snap.exists()&&snap.data().photoUrl)adminDpPreview.src=snap.data().photoUrl;else if(user.photoURL)adminDpPreview.src=user.photoURL}
adminDpInput?.addEventListener("change",()=>{const f=adminDpInput.files?.[0];if(!f)return;if(f.size>5*1024*1024){alert("Image must be 5 MB or smaller.");adminDpInput.value="";return}adminDpPreview.src=URL.createObjectURL(f);saveAdminDpBtn.disabled=false});
saveAdminDpBtn?.addEventListener("click",async()=>{const f=adminDpInput.files?.[0];if(!f||!auth.currentUser)return;saveAdminDpBtn.disabled=true;saveAdminDpBtn.textContent="Uploading...";try{const url=await uploadToCloudinary(f,`bayiira/admin/${auth.currentUser.uid}`);await setDoc(doc(db,"adminProfiles",auth.currentUser.uid),{email:auth.currentUser.email,photoUrl:url,updatedAt:serverTimestamp()},{merge:true});adminDpPreview.src=url;msg(adminProfileMsg,"Profile picture updated successfully.");setTimeout(()=>hide(adminProfileMsg),3000)}catch(e){alert(e.message);saveAdminDpBtn.disabled=false}finally{saveAdminDpBtn.textContent="Save Profile Picture"}});

function listenMembers(){const q=query(collection(db,"members"),orderBy("submittedAt","desc"));onSnapshot(q,snap=>{members=snap.docs.map(d=>({id:d.id,...d.data()}));render()},err=>{console.error(err);membersBody.innerHTML=`<tr><td colspan="6" class="empty">Unable to load registrations. Check Firestore Rules.</td></tr>`})}
function render(){const term=search.value.trim().toLowerCase(),filter=statusFilter.value;const filtered=members.filter(m=>{const hay=[m.fullName,m.firstName,m.lastName,m.phone,m.email,m.district,m.id,m.registrationNumber].join(" ").toLowerCase();return(!term||hay.includes(term))&&(filter==="all"||((m.status||"pending")===filter))});const counts={pending:0,approved:0,rejected:0};members.forEach(m=>counts[m.status||"pending"]=(counts[m.status||"pending"]||0)+1);document.getElementById("totalCount").textContent=members.length;document.getElementById("pendingCount").textContent=counts.pending||0;document.getElementById("approvedCount").textContent=counts.approved||0;document.getElementById("rejectedCount").textContent=counts.rejected||0;if(!filtered.length){membersBody.innerHTML=`<tr><td colspan="6" class="empty">No registrations found.</td></tr>`;return}membersBody.innerHTML=filtered.map(m=>`<tr><td>${m.passportPhotoUrl?`<img class="member-thumb" src="${esc(m.passportPhotoUrl)}" alt="">`:""}<strong>${esc(m.fullName||"Unnamed")}</strong><br><small>${esc(m.email||"No email")}</small></td><td>${esc(m.phone||"—")}</td><td>${esc(m.membershipType||"—")}<br>${esc(m.membershipCategory||"—")}</td><td>${esc(dateText(m.submittedAt))}</td><td>${statusBadge(m.status)}${m.registrationNumber?`<br><small>${esc(m.registrationNumber)}</small>`:""}</td><td><div class="actions"><button class="btn btn-secondary btn-small" data-action="view" data-id="${esc(m.id)}">View</button>${m.status!=="approved"?`<button class="btn btn-primary btn-small" data-action="approve" data-id="${esc(m.id)}">Approve</button>`:""}${m.status!=="rejected"?`<button class="btn btn-danger btn-small" data-action="reject" data-id="${esc(m.id)}">Reject</button>`:""}${m.status==="approved"?`<button class="btn btn-secondary btn-small" data-action="id" data-id="${esc(m.id)}">Download ID</button>`:""}<button class="btn btn-danger btn-small" data-action="delete" data-id="${esc(m.id)}">Delete</button></div></td></tr>`).join("")}

membersBody.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;const m=members.find(x=>x.id===b.dataset.id);if(!m)return;const action=b.dataset.action;if(action==="view"){openDetails(m);return}if(action==="id"){openId(m);return}if(action==="approve"){if(!confirm(`Approve ${m.fullName||"this member"}? A registration number will be assigned automatically.`))return;try{await approveMember(m.id);alert("Member approved successfully.")}catch(err){console.error(err);alert("Approval failed: "+err.message)}return}if(action==="reject"){if(!confirm(`Set ${m.fullName||"this member"} as rejected?`))return;try{await updateDoc(doc(db,"members",m.id),{status:"rejected",updatedAt:serverTimestamp()})}catch(err){alert("Could not update this member: "+err.message)}return}if(action==="delete"){const ok=confirm(`Permanently delete ${m.fullName||"this member"} from Firebase?`);if(!ok)return;const pw=prompt("Enter administrator password to permanently delete this member:");if(pw===null)return;if(!pw){alert("Password is required.");return}try{const user=auth.currentUser;await reauthenticateWithCredential(user,EmailAuthProvider.credential(user.email,pw));await deleteDoc(doc(db,"members",m.id));alert("Member deleted permanently from Firebase.")}catch(err){alert(err.code==="auth/invalid-credential"?"Incorrect administrator password. Member was NOT deleted.":"Delete failed. Member was NOT deleted.")}}});

async function approveMember(memberId){const memberRef=doc(db,"members",memberId);const counterRef=doc(db,"settings","registrationCounter");await runTransaction(db,async tx=>{const [memberSnap,counterSnap]=await Promise.all([tx.get(memberRef),tx.get(counterRef)]);if(!memberSnap.exists())throw new Error("Member no longer exists.");const member=memberSnap.data();if(member.status==="approved")return;const next=(counterSnap.exists()?Number(counterSnap.data().lastNumber||0):0)+1;const registrationNumber=`BOR/2026/${String(next).padStart(3,"0")}`;tx.set(counterRef,{lastNumber:next,updatedAt:serverTimestamp()},{merge:true});tx.update(memberRef,{status:"approved",registrationNumber,approvedAt:serverTimestamp(),updatedAt:serverTimestamp()})})}

function openDetails(m){const entries=Object.entries(m).filter(([k])=>k!=="id"&&k!=="updatedAt");detailBody.innerHTML=`<div class="detail-photo">${m.passportPhotoUrl?`<img src="${esc(m.passportPhotoUrl)}" alt="Passport photo">`:""}</div><div class="detail-grid">${entries.map(([k,v])=>{let value=v;if(k==="submittedAt"||k==="approvedAt")value=dateText(v);if(k==="status")value=statusBadge(v);return `<div class="detail"><small>${esc(k.replace(/([A-Z])/g," $1"))}</small><div>${k==="status"?value:esc(value)}</div></div>`}).join("")}</div>`;modal.classList.add("open")}
document.getElementById("closeModal").onclick=()=>modal.classList.remove("open");modal.addEventListener("click",e=>{if(e.target===modal)modal.classList.remove("open")});search.addEventListener("input",render);statusFilter.addEventListener("change",render);document.getElementById("refreshBtn").onclick=()=>render();

function openId(m){if(m.status!=="approved"||!m.registrationNumber){alert("Only approved members with a registration number can receive an ID.");return}selectedMember=m;const fullName=(m.fullName||`${m.firstName||""} ${m.lastName||""}`).trim()||"—";idFullName.textContent=fullName;idRegNo.textContent=m.registrationNumber;idMembership.textContent=m.membershipType||"Member";idCategory.textContent=m.membershipCategory||"—";idPhone.textContent=m.phone||"—";idPassport.src=m.passportPhotoUrl||"logo.png";idSignature.textContent=(m.signatureName||m.lastName||"Member").trim();idModal.classList.add("open");requestAnimationFrame(()=>{if(window.JsBarcode){JsBarcode(idBarcode,m.registrationNumber,{format:"CODE128",displayValue:false,height:58,width:2,margin:0,lineColor:"#102f4f",background:"transparent"});idBarcodeText.textContent=m.registrationNumber;}if(window.QRCode){idQr.innerHTML="";new QRCode(idQr,{text:`BAYIIRA|${m.registrationNumber}|${fullName}|${m.phone||""}`,width:88,height:88,colorDark:"#123b72",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.M})}})}
document.getElementById("closeIdModal").onclick=()=>idModal.classList.remove("open");idModal.addEventListener("click",e=>{if(e.target===idModal)idModal.classList.remove("open")});
document.getElementById("downloadIdBtn").onclick=async()=>{if(!selectedMember)return;const card=document.getElementById("memberIdCard");const btn=document.getElementById("downloadIdBtn");btn.disabled=true;btn.textContent="Preparing PNG...";try{const canvas=await html2canvas(card,{scale:3,useCORS:true,backgroundColor:"#ffffff",logging:false,width:800,height:600,windowWidth:800,windowHeight:600});const link=document.createElement("a");link.download=`${selectedMember.registrationNumber.replaceAll("/","-")}-${(selectedMember.fullName||"member").replaceAll(" ","-")}-ID.png`;link.href=canvas.toDataURL("image/png");link.click()}catch(e){console.error(e);alert("Could not create the PNG. Please try again.")}finally{btn.disabled=false;btn.textContent="Download ID as PNG"}};
