(function(){
  "use strict";
  const config=window.BAYIIRA_FIREBASE_CONFIG, ADMIN_EMAIL=(window.BAYIIRA_ADMIN_EMAIL||"").toLowerCase();
  if(!window.firebase||!config){console.error("Bayiira: Firebase SDK/config failed to load.");return;}
  if(!firebase.apps.length) firebase.initializeApp(config);
  const db=firebase.firestore(), auth=firebase.auth();
  const $=id=>document.getElementById(id);
  const loginBtn=$("loginBtn"),email=$("email"),password=$("password"),loginView=$("loginView"),dashboardView=$("dashboardView"),loginError=$("loginError"),membersBody=$("membersBody"),search=$("search"),statusFilter=$("statusFilter");
  const detailModal=$("detailModal"),detailBody=$("detailBody"),closeModal=$("closeModal"),refreshBtn=$("refreshBtn"),logoutBtn=$("logoutBtn");
  const idModal=$("idModal"),closeIdModal=$("closeIdModal"),downloadIdBtn=$("downloadIdBtn");
  const idPassport=$("idPassport"),idFullName=$("idFullName"),idRegNo=$("idRegNo"),idMembership=$("idMembership"),idCategory=$("idCategory"),idPhone=$("idPhone"),idLocation=$("idLocation"),idSubCounty=$("idSubCounty"),idCounty=$("idCounty"),idDistrict=$("idDistrict"),idValidity=$("idValidity"),idMemberSignature=$("idMemberSignature"),idSecretarySignature=$("idSecretarySignature"),idChairpersonSignature=$("idChairpersonSignature"),idBarcode=$("idBarcode"),idQr=$("idQr");
  const adminDpInput=$("adminDpInput"),adminDpPreview=$("adminDpPreview"),saveAdminDpBtn=$("saveAdminDpBtn"),adminProfileMsg=$("adminProfileMsg");
  let members=[],selectedMember=null,unsubscribeMembers=null,explicitLoginThisLoad=false,sessionTimer=null;
  function msg(el,text){if(!el)return;el.textContent=text;el.style.display="block";} function hide(el){if(el){el.textContent="";el.style.display="none";}}
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));}
  function dateText(v){if(!v)return "—";try{return typeof v.toDate==="function"?v.toDate().toLocaleString():new Date(v).toLocaleString();}catch{return String(v);}}
  function statusBadge(s){s=s||"pending";return '<span class="badge badge-'+esc(s)+'">'+esc(s.toUpperCase())+'</span>';}
  if(!loginBtn||!email||!password||!loginView||!dashboardView||!loginError||!membersBody||!search||!statusFilter||!detailModal||!detailBody){console.error("Bayiira admin: required dashboard elements are missing.");return;}

  async function forceFreshAuth(){
    explicitLoginThisLoad=false;
    try{await auth.setPersistence(firebase.auth.Auth.Persistence.NONE);}catch(e){console.warn("Could not set non-persistent auth persistence:",e);}
    try{await auth.signOut();}catch(e){}
    dashboardView.classList.add("hidden");loginView.classList.remove("hidden");
  }
  function startSessionTimer(){clearTimeout(sessionTimer);sessionTimer=setTimeout(async()=>{alert("Administrator session expired. Please log in again.");await doLogout();},30*60*1000);}
  function activity(){if(explicitLoginThisLoad)startSessionTimer();}
  ["click","keydown","touchstart","mousemove"].forEach(ev=>document.addEventListener(ev,activity,{passive:true}));
  async function signIn(){
    hide(loginError);
    if(!email.value.trim()||!password.value){msg(loginError,"Enter the administrator email and password.");return;}
    loginBtn.disabled=true;loginBtn.textContent="SIGNING IN...";explicitLoginThisLoad=true;
    try{
      const cred=await auth.signInWithEmailAndPassword(email.value.trim(),password.value);
      if(!cred.user.email||cred.user.email.toLowerCase()!==ADMIN_EMAIL){await auth.signOut();throw new Error("This account is not authorized as administrator.");}
      showDashboard(cred.user);
    }catch(e){
      explicitLoginThisLoad=false;
      console.error("Administrator login failed:",e);const code=e&&e.code||"";let text=e&&e.message||"Login failed. Please try again.";
      if(code==="auth/invalid-login-credentials"||code==="auth/wrong-password"||code==="auth/invalid-credential")text="Invalid administrator email or password.";
      if(code==="auth/user-not-found")text="Administrator account was not found.";
      if(code==="auth/too-many-requests")text="Too many attempts. Please wait and try again later.";
      msg(loginError,text);
    }finally{loginBtn.disabled=false;loginBtn.textContent="LOGIN";}
  }
  loginBtn.addEventListener("click",signIn);password.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();signIn();}});
  function showDashboard(user){if(!explicitLoginThisLoad)return;loginView.classList.add("hidden");dashboardView.classList.remove("hidden");loadAdminProfile(user);listenMembers();startSessionTimer();}
  auth.onAuthStateChanged(user=>{
    if(user&&user.email&&user.email.toLowerCase()===ADMIN_EMAIL&&explicitLoginThisLoad){showDashboard(user);}
    else{dashboardView.classList.add("hidden");loginView.classList.remove("hidden");if(user)auth.signOut().catch(()=>{});}
  });
  async function doLogout(){clearTimeout(sessionTimer);explicitLoginThisLoad=false;if(unsubscribeMembers)unsubscribeMembers();unsubscribeMembers=null;try{await auth.signOut();}catch(e){}dashboardView.classList.add("hidden");loginView.classList.remove("hidden");password.value="";hide(loginError);}
  logoutBtn&&logoutBtn.addEventListener("click",async()=>{logoutBtn.disabled=true;try{await doLogout();}finally{logoutBtn.disabled=false;}});
  forceFreshAuth();

  async function imageDataUrl(file,maxW=360,maxH=360,quality=.72){if(!file)throw new Error("Please select an image.");if(file.size>5*1024*1024)throw new Error("Image must be 5 MB or smaller.");return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{let w=img.naturalWidth,h=img.naturalHeight,scale=Math.min(1,maxW/w,maxH/h);w=Math.max(1,Math.round(w*scale));h=Math.max(1,Math.round(h*scale));const c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,w,h);x.drawImage(img,0,0,w,h);resolve(c.toDataURL("image/jpeg",quality));};img.onerror=()=>reject(new Error("The image could not be read."));img.src=r.result;};r.onerror=()=>reject(new Error("The image could not be read."));r.readAsDataURL(file);});}
  async function loadAdminProfile(user){$("adminProfileEmail").textContent=user.email||ADMIN_EMAIL;try{const snap=await db.collection("adminProfiles").doc(user.uid).get();if(snap.exists&&snap.data().photoUrl)adminDpPreview.src=snap.data().photoUrl;else if(user.photoURL)adminDpPreview.src=user.photoURL;}catch(e){console.warn("Admin profile could not be loaded:",e);}}
  adminDpInput&&adminDpInput.addEventListener("change",()=>{const f=adminDpInput.files&&adminDpInput.files[0];if(!f)return;if(f.size>5*1024*1024){alert("Image must be 5 MB or smaller.");adminDpInput.value="";return;}const r=new FileReader();r.onload=()=>{adminDpPreview.src=r.result;};r.readAsDataURL(f);saveAdminDpBtn.disabled=false;});
  saveAdminDpBtn&&saveAdminDpBtn.addEventListener("click",async()=>{const f=adminDpInput.files&&adminDpInput.files[0],user=auth.currentUser;if(!f||!user)return;saveAdminDpBtn.disabled=true;saveAdminDpBtn.textContent="Saving...";try{const url=await imageDataUrl(f);await db.collection("adminProfiles").doc(user.uid).set({email:user.email,photoUrl:url,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});adminDpPreview.src=url;msg(adminProfileMsg,"Profile picture updated successfully.");await writeAudit("UPDATE_ADMIN_PROFILE",{adminUid:user.uid});setTimeout(()=>hide(adminProfileMsg),3000);}catch(e){alert(e.message);}finally{saveAdminDpBtn.disabled=false;saveAdminDpBtn.textContent="Save Profile Picture";}});

  function listenMembers(){if(unsubscribeMembers)unsubscribeMembers();unsubscribeMembers=db.collection("members").orderBy("submittedAt","desc").onSnapshot(snap=>{members=snap.docs.map(d=>({id:d.id,...d.data()}));render();},err=>{console.error("Member listener failed:",err);membersBody.innerHTML='<tr><td colspan="6" class="empty">Unable to load registrations. Check Firestore Rules and your internet connection.</td></tr>';});}
  function render(){const term=search.value.trim().toLowerCase(),filter=statusFilter.value;const filtered=members.filter(m=>{const hay=[m.fullName,m.firstName,m.lastName,m.phone,m.email,m.district,m.parish,m.subCounty,m.id,m.registrationNumber].join(" ").toLowerCase();return(!term||hay.includes(term))&&(filter==="all"||((m.status||"pending")===filter)||(filter==="active"&&membershipState(m)==="ACTIVE")||(filter==="expired"&&membershipState(m)==="EXPIRED"));});const counts={pending:0,approved:0,rejected:0,active:0,expired:0};members.forEach(m=>{const st=m.status||"pending";counts[st]=(counts[st]||0)+1;const ms=membershipState(m);if(ms==="ACTIVE")counts.active++;if(ms==="EXPIRED")counts.expired++;});$("totalCount").textContent=members.length;$("pendingCount").textContent=counts.pending||0;$("approvedCount").textContent=counts.approved||0;$("rejectedCount").textContent=counts.rejected||0;$("activeCount").textContent=counts.active||0;$("expiredCount").textContent=counts.expired||0;if(!filtered.length){membersBody.innerHTML='<tr><td colspan="6" class="empty">No registrations found.</td></tr>';return;}membersBody.innerHTML=filtered.map(m=>'<tr><td>'+(m.passportPhotoUrl?'<img class="member-thumb" src="'+esc(m.passportPhotoUrl)+'" alt="">':"")+ '<strong>'+esc(m.fullName||"Unnamed")+'</strong><br><small>'+esc(m.email||"No email")+'</small></td><td>'+esc(m.phone||"—")+'</td><td>'+esc(m.membershipType||"—")+'<br>'+esc(m.membershipCategory||"—")+'</td><td>'+esc(dateText(m.submittedAt))+'</td><td>'+statusBadge(m.status)+"<br><small>"+esc(membershipState(m))+"</small>"+(m.registrationNumber?'<br><small>'+esc(m.registrationNumber)+'</small>':"")+'</td><td><div class="actions"><button class="btn btn-secondary btn-small" data-action="view" data-id="'+esc(m.id)+'">View</button>'+(m.status!=="approved"?'<button class="btn btn-primary btn-small" data-action="approve" data-id="'+esc(m.id)+'">Approve</button>':"")+(m.status!=="rejected"?'<button class="btn btn-danger btn-small" data-action="reject" data-id="'+esc(m.id)+'">Reject</button>':"")+(m.status==="approved"?'<button class="btn btn-secondary btn-small" data-action="id" data-id="'+esc(m.id)+'">Download ID</button>':"")+'<button class="btn btn-danger btn-small" data-action="delete" data-id="'+esc(m.id)+'">Delete</button></div></td></tr>').join("");}
  membersBody.addEventListener("click",async e=>{const b=e.target.closest("button[data-action]");if(!b)return;const m=members.find(x=>x.id===b.dataset.id);if(!m)return;const a=b.dataset.action;if(a==="view")return openDetails(m);if(a==="id")return openId(m);if(a==="approve"){if(!confirm("Approve "+(m.fullName||"this member")+"?"))return;try{await approveMember(m.id);alert("Member approved successfully.");}catch(err){console.error(err);alert("Approval failed: "+err.message);}return;}if(a==="reject"){const reason=prompt("Reason for rejection (optional):",m.rejectionReason||"");if(reason===null)return;try{await db.collection("members").doc(m.id).update({status:"rejected",membershipStatus:"rejected",rejectionReason:reason.trim(),rejectedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});await writeAudit("REJECT_MEMBER",{memberId:m.id,reason:reason.trim()});}catch(err){alert("Could not update this member: "+err.message);}return;}if(a==="delete"){if(!confirm("Permanently delete "+(m.fullName||"this member")+" from Firebase?"))return;const pw=prompt("Enter administrator password to permanently delete this member:");if(pw===null)return;if(!pw){alert("Password is required.");return;}try{const user=auth.currentUser;if(!user)throw new Error("Administrator session expired.");const cred=firebase.auth.EmailAuthProvider.credential(user.email,pw);await user.reauthenticateWithCredential(cred);await db.collection("members").doc(m.id).delete();await writeAudit("DELETE_MEMBER",{memberId:m.id});alert("Member deleted permanently from Firebase.");}catch(err){alert(err.code==="auth/invalid-credential"?"Incorrect administrator password. Member was NOT deleted.":"Delete failed. Member was NOT deleted.");}}});
  async function writeAudit(action,extra){try{const u=auth.currentUser;if(!u)return;await db.collection("auditLogs").doc().set(Object.assign({action,adminEmail:u.email,createdAt:firebase.firestore.FieldValue.serverTimestamp()},extra||{}));}catch(e){console.warn("Audit log failed:",e);}}
  async function approveMember(memberId){
    const memberRef=db.collection("members").doc(memberId),counterRef=db.collection("settings").doc("membershipCounter");
    await db.runTransaction(async tx=>{
      const memberSnap=await tx.get(memberRef); const counterSnap=await tx.get(counterRef);
      if(!memberSnap.exists)throw new Error("Member no longer exists.");
      const member=memberSnap.data(); if(member.status==="approved"&&member.registrationNumber)return;
      const year=new Date().getFullYear();const lastYear=counterSnap.exists?Number(counterSnap.data().year||0):0;const lastNumber=counterSnap.exists?Number(counterSnap.data().lastNumber||0):0;const next=(lastYear===year?lastNumber:0)+1;const registrationNumber="BOR-"+year+"-H"+String(next).padStart(2,"0");const validUntil=String(year+2);
      tx.set(counterRef,{year,lastNumber:next,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});
      tx.update(memberRef,{status:"approved",membershipStatus:"active",registrationNumber,approvedAt:firebase.firestore.FieldValue.serverTimestamp(),issuedYear:year,validFrom:String(year),validUntil,rejectionReason:firebase.firestore.FieldValue.delete(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});
      tx.set(db.collection("verifications").doc(registrationNumber),{membershipNumber:registrationNumber,fullName:member.fullName||((member.firstName||"")+" "+(member.lastName||"")).trim(),status:"ACTIVE",membershipType:member.membershipType||"Member",membershipCategory:member.membershipCategory||"New",validFrom:String(year),validUntil,verifiedAt:firebase.firestore.FieldValue.serverTimestamp()});
      tx.set(db.collection("auditLogs").doc(),{action:"APPROVE_MEMBER",memberId,registrationNumber,adminEmail:auth.currentUser&&auth.currentUser.email||ADMIN_EMAIL,createdAt:firebase.firestore.FieldValue.serverTimestamp()});
    });
  }
  function openDetails(m){
    const photo=m.passportPhotoUrl||m.passportPhoto||m.photoUrl||m.photo||"";
    const entries=Object.entries(m).filter(([k])=>{
      if(["id","updatedAt"].includes(k)) return false;
      if(/(photo|image|passport).*url|^photoUrl$|^passportPhotoUrl$|^passportPhoto$|^photo$/i.test(k)) return false;
      return true;
    });
    const photoBlock=photo?`<div class="detail-photo"><img src="${esc(photo)}" alt="Passport photo"><div class="photo-label">Passport Photo</div></div>`:`<div class="detail-photo"><div class="photo-placeholder">No passport photo</div></div>`;
    detailBody.innerHTML=photoBlock+'<div class="detail-grid">'+entries.map(([k,v])=>{
      let value=v;
      if(k==="submittedAt"||k==="approvedAt"||k==="rejectedAt") value=dateText(v);
      if(k==="status") value=statusBadge(v);
      if(typeof value==='string' && /^https?:\/\//i.test(value)) value='Stored securely';
      return '<div class="detail"><small>'+esc(k.replace(/([A-Z])/g," $1"))+'</small><div>'+(k==="status"?value:esc(String(value??"—")))+'</div></div>';
    }).join('')+'</div>';
    detailModal.classList.add("open");
  }
  closeModal&&closeModal.addEventListener("click",()=>detailModal.classList.remove("open"));detailModal.addEventListener("click",e=>{if(e.target===detailModal)detailModal.classList.remove("open")});search.addEventListener("input",render);statusFilter.addEventListener("change",render);refreshBtn&&refreshBtn.addEventListener("click",render);$("exportCsvBtn")&&$("exportCsvBtn").addEventListener("click",exportCsv);$("printReportBtn")&&$("printReportBtn").addEventListener("click",printReport);$("backupJsonBtn")&&$("backupJsonBtn").addEventListener("click",backupJson);$("auditBtn")&&$("auditBtn").addEventListener("click",showAuditLogs);
  function membershipState(m){if(m.status!=="approved")return(m.status||"pending").toUpperCase();const y=Number(m.validUntil||0),now=new Date().getFullYear();if(y&&y<now)return"EXPIRED";if(y&&y===now)return"EXPIRING SOON";return"ACTIVE";}
  function csvEscape(v){return '"'+String(v==null?"":v).replace(/"/g,'""')+'"';}
  function exportCsv(){const rows=[['Membership No','Full Name','Phone','Email','Membership Type','Category','Status','Valid Until','Parish/Ward','Sub-county/Town Council','County/Division','District/City','Submitted']];members.forEach(m=>rows.push([m.registrationNumber||'',m.fullName||'',m.phone||'',m.email||'',m.membershipType||'',m.membershipCategory||'',membershipState(m),m.validUntil||'',m.parish||'',m.subCounty||'',m.county||'',m.district||'',dateText(m.submittedAt)]));downloadBlob(rows.map(r=>r.map(csvEscape).join(',')).join('\n'),'Bayiira_Membership_Register.csv','text/csv;charset=utf-8');writeAudit('EXPORT_REGISTER_CSV');}
  function backupJson(){const payload={system:'Bayiira Membership System',exportedAt:new Date().toISOString(),members:members};downloadBlob(JSON.stringify(payload,null,2),'Bayiira_Membership_Backup_'+new Date().toISOString().slice(0,10)+'.json','application/json');writeAudit('EXPORT_REGISTER_BACKUP_JSON');}
  function downloadBlob(content,name,type){const blob=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function printReport(){const rows=members.map(m=>`<tr><td>${esc(m.registrationNumber||'—')}</td><td>${esc(m.fullName||'')}</td><td>${esc(m.phone||'')}</td><td>${esc(membershipState(m))}</td><td>${esc(m.validUntil||'—')}</td></tr>`).join('');const w=window.open('','_blank','width=1000,height=700');if(!w)return;w.document.write(`<!doctype html><html><head><title>Bayiira Membership Register</title><style>body{font-family:Arial;padding:25px;color:#173b2a}h1{color:#08753a}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:8px;text-align:left}th{background:#08753a;color:#fff}</style></head><body><h1>BAYIIRA MEMBERSHIP ORGANISATION</h1><p>Membership Register — ${new Date().toLocaleDateString()}</p><table><thead><tr><th>Membership No.</th><th>Member</th><th>Phone</th><th>Status</th><th>Valid Until</th></tr></thead><tbody>${rows}</tbody></table><script>window.print();<\/script></body></html>`);w.document.close();writeAudit('PRINT_REGISTER');}
  async function showAuditLogs(){try{const snap=await db.collection('auditLogs').orderBy('createdAt','desc').limit(100).get();const rows=snap.docs.map(d=>{const x=d.data();return `<tr><td>${esc(dateText(x.createdAt))}</td><td>${esc(x.action||'')}</td><td>${esc(x.registrationNumber||x.memberId||'')}</td><td>${esc(x.adminEmail||'')}</td></tr>`;}).join('');const w=window.open('','_blank','width=1000,height=700');if(!w)return;w.document.write(`<!doctype html><html><head><title>Bayiira Audit Log</title><style>body{font-family:Arial;padding:25px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:8px;text-align:left}th{background:#08753a;color:#fff}</style></head><body><h1>Bayiira Audit Log</h1><table><thead><tr><th>Date</th><th>Action</th><th>Member/Reference</th><th>Admin</th></tr></thead><tbody>${rows||'<tr><td colspan="4">No audit records.</td></tr>'}</tbody></table></body></html>`);w.document.close();}catch(e){alert('Could not load audit logs: '+e.message);}}
  function generateMemberSignature(lastName){const text=(lastName||"Member").trim()||"Member",c=document.createElement("canvas");c.width=520;c.height=150;const x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);x.fillStyle="#162a3d";x.strokeStyle="#162a3d";x.lineWidth=3;x.lineCap="round";x.font='italic 70px "Brush Script MT","Segoe Script",cursive';x.textBaseline="middle";x.fillText(text,30,75);x.beginPath();x.moveTo(25,113);x.quadraticCurveTo(240,145,490,103);x.stroke();return c.toDataURL("image/png");}
  function openId(m){if(m.status!=="approved"||!m.registrationNumber){alert("Only approved members with a registration number can receive an ID.");return;}selectedMember=m;const full=(m.fullName||((m.firstName||"")+" "+(m.lastName||"")).trim()||"—"),last=(m.lastName||full.split(/\s+/).pop()||"Member").trim();idFullName.textContent=full;idRegNo.textContent=m.registrationNumber;idMembership.textContent=m.membershipType||"Member";idCategory.textContent=m.membershipCategory||"—";idPhone.textContent=m.phone||"—";idLocation.textContent=m.location||m.parish||"—";idSubCounty.textContent=m.subCounty||"—";idCounty.textContent=m.county||"—";idDistrict.textContent=m.district||"—";idValidity.textContent=m.validUntil||m.membershipValidity||"2026 – 2028";idPassport.src=m.passportPhotoUrl||"logo.png";idMemberSignature.src=generateMemberSignature(last);idSecretarySignature.src="masereka-felex-signature.png";idChairpersonSignature.src="muhindo-enock-signature.png";idModal.classList.add("open");setTimeout(()=>{if(window.JsBarcode)window.JsBarcode(idBarcode,m.registrationNumber,{format:"CODE128",displayValue:false,height:42,width:1.8,margin:0,lineColor:"#123b72",background:"transparent"});if(window.QRCode){idQr.innerHTML="";new QRCode(idQr,{text:(new URL("verify.html?member="+encodeURIComponent(m.registrationNumber),window.location.href)).href,width:88,height:88,colorDark:"#123b72",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.M});}},50);}
  closeIdModal&&closeIdModal.addEventListener("click",()=>idModal.classList.remove("open"));idModal.addEventListener("click",e=>{if(e.target===idModal)idModal.classList.remove("open")});
  downloadIdBtn&&downloadIdBtn.addEventListener("click",async()=>{if(!selectedMember)return;downloadIdBtn.disabled=true;downloadIdBtn.textContent="Preparing PNG...";try{await new Promise(r=>setTimeout(r,400));const card=$("memberIdCard"),canvas=await html2canvas(card,{scale:3,useCORS:true,allowTaint:false,backgroundColor:"#fff",logging:false,width:800,height:600,windowWidth:800,windowHeight:600,imageTimeout:15000});const a=document.createElement("a"),safe=(selectedMember.fullName||"member").replace(/[^a-z0-9]+/gi,"-");a.download=(selectedMember.registrationNumber||"member").replace(/\//g,"-")+"-"+safe+"-ID.png";a.href=canvas.toDataURL("image/png");document.body.appendChild(a);a.click();a.remove();writeAudit('DOWNLOAD_MEMBER_ID',{memberId:selectedMember.id,registrationNumber:selectedMember.registrationNumber});}catch(e){console.error(e);alert("Could not create the PNG. Please try again.");}finally{downloadIdBtn.disabled=false;downloadIdBtn.textContent="Download ID as PNG";}});
})();
